name: Apply Supabase Migrations

on:
  workflow_dispatch:

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Run migrations
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }} # e.g. postgres://user:pass@host:5432/postgres
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "Set SUPABASE_DB_URL in GitHub Secrets"
            exit 1
          fi
          for f in supabase/migrations/*.sql; do
            echo "Applying $f"
            psql "$SUPABASE_DB_URL" -f "$f"
          done
